[build]
  command = "npm run build"
  functions = "dist/server"

[build.environment]
  API_KEY = "RXUSccOoxFCSL75oH0GCg"

[[headers]]
  for = '''
  "/search" 
  "/author"
  '''
    [headers.values]
    Access-Control-Allow-Origin = "https://infallible-wilson-4e1a09.netlify.app/"
[[headers]]
  for = "/author-followers"
    [headers.values]
    Access-Control-Allow-Origin = "https://infallible-wilson-4e1a09.netlify.app/"
    Access-Control-Allow-Headers = "Accept"
    Access-Control-Allow-Credentials = "true"
  
[[redirects]]
  from = "/*"
  to = "/"
  status = 200

